"""initial schema

Revision ID: 018a435b9e03
Revises:
Create Date: 2026-05-01 19:39:12.806847

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "018a435b9e03"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("robots_respect", sa.Boolean(), nullable=False),
        sa.Column("js_render", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain", name="uq_projects_domain"),
    )
    op.create_index(op.f("ix_projects_domain"), "projects", ["domain"], unique=False)
    op.create_table(
        "backlinks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("anchor", sa.String(length=2048), nullable=True),
        sa.Column("source_provider", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "source_url", "target_url", name="uq_backlinks_source_target"
        ),
    )
    op.create_index(
        "ix_backlinks_project_status", "backlinks", ["project_id", "status"], unique=False
    )
    op.create_table(
        "crawls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="crawl_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages_crawled", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("score_tech", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("score_struct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("score_content", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("score_overall", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crawls_project_id"), "crawls", ["project_id"], unique=False)
    op.create_table(
        "keywords",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=512), nullable=False),
        sa.Column("country", sa.String(length=8), nullable=False),
        sa.Column("device", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "keyword", "country", name="uq_keywords_project_keyword"),
    )
    op.create_index(op.f("ix_keywords_project_id"), "keywords", ["project_id"], unique=False)
    op.create_table(
        "sitemaps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("urls_count", sa.Integer(), nullable=False),
        sa.Column("fetch_error", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sitemaps_project_id"), "sitemaps", ["project_id"], unique=False)
    op.create_table(
        "keyword_rankings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.Column("checked_on", sa.Date(), nullable=False),
        sa.Column("position", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("ctr", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("landing_url", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(["keyword_id"], ["keywords.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_kw_rankings_keyword_date",
        "keyword_rankings",
        ["keyword_id", "checked_on"],
        unique=False,
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crawl_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("html_size", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=1024), nullable=True),
        sa.Column("meta_description", sa.String(length=2048), nullable=True),
        sa.Column("meta_robots", sa.String(length=255), nullable=True),
        sa.Column("canonical_url", sa.String(length=2048), nullable=True),
        sa.Column("h1", sa.String(length=2048), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=True),
        sa.Column("is_indexable", sa.Boolean(), nullable=True),
        sa.Column("fetch_error", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pages_content_hash", "pages", ["content_hash"], unique=False)
    op.create_index("ix_pages_crawl_url", "pages", ["crawl_id", "url"], unique=False)
    op.create_table(
        "content_blocks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("block_hash", sa.String(length=128), nullable=False),
        sa.Column("text_excerpt", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_content_blocks_hash", "content_blocks", ["block_hash"], unique=False)
    op.create_index(op.f("ix_content_blocks_page_id"), "content_blocks", ["page_id"], unique=False)
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("src", sa.String(length=2048), nullable=False),
        sa.Column("alt", sa.String(length=2048), nullable=True),
        sa.Column("has_alt", sa.Boolean(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_page_id"), "images", ["page_id"], unique=False)
    op.create_table(
        "issues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crawl_id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=True),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column(
            "category",
            sa.Enum("TECH_META", "STRUCTURE", "CONTENT", name="issue_category"),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "IMPORTANT", "TIP", name="issue_severity"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_issues_crawl_rule", "issues", ["crawl_id", "rule_id"], unique=False)
    op.create_index("ix_issues_crawl_severity", "issues", ["crawl_id", "severity"], unique=False)
    op.create_index(op.f("ix_issues_page_id"), "issues", ["page_id"], unique=False)
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crawl_id", sa.Integer(), nullable=False),
        sa.Column("source_page_id", sa.Integer(), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("anchor_text", sa.String(length=2048), nullable=True),
        sa.Column("rel", sa.String(length=255), nullable=True),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("is_followed", sa.Boolean(), nullable=False),
        sa.Column("target_status_code", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_links_crawl_internal", "links", ["crawl_id", "is_internal"], unique=False)
    op.create_index(op.f("ix_links_source_page_id"), "links", ["source_page_id"], unique=False)
    op.create_index("ix_links_target_url", "links", ["target_url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_links_target_url", table_name="links")
    op.drop_index(op.f("ix_links_source_page_id"), table_name="links")
    op.drop_index("ix_links_crawl_internal", table_name="links")
    op.drop_table("links")
    op.drop_index(op.f("ix_issues_page_id"), table_name="issues")
    op.drop_index("ix_issues_crawl_severity", table_name="issues")
    op.drop_index("ix_issues_crawl_rule", table_name="issues")
    op.drop_table("issues")
    op.drop_index(op.f("ix_images_page_id"), table_name="images")
    op.drop_table("images")
    op.drop_index(op.f("ix_content_blocks_page_id"), table_name="content_blocks")
    op.drop_index("ix_content_blocks_hash", table_name="content_blocks")
    op.drop_table("content_blocks")
    op.drop_index("ix_pages_crawl_url", table_name="pages")
    op.drop_index("ix_pages_content_hash", table_name="pages")
    op.drop_table("pages")
    op.drop_index("ix_kw_rankings_keyword_date", table_name="keyword_rankings")
    op.drop_table("keyword_rankings")
    op.drop_index(op.f("ix_sitemaps_project_id"), table_name="sitemaps")
    op.drop_table("sitemaps")
    op.drop_index(op.f("ix_keywords_project_id"), table_name="keywords")
    op.drop_table("keywords")
    op.drop_index(op.f("ix_crawls_project_id"), table_name="crawls")
    op.drop_table("crawls")
    op.drop_index("ix_backlinks_project_status", table_name="backlinks")
    op.drop_table("backlinks")
    op.drop_index(op.f("ix_projects_domain"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
